# Generated by Django 5.0.3 on 2024-03-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=50, verbose_name='Género'),
            preserve_default=False,
        ),
    ]
